### ISSUE TITLE
[Feature Request] excludeLosses and excludeKills

### ISSUE THREAD

**Issue by sirlattwich** [eveopsec/zk2s#20]
Hey there o/

Your software compiles and runs perfectly fine on a Raspberry Pi (ARM) with autostart via systemd unit file.

I would like to request a feature that would allow easy creation of separate killmail and lossmail channels.

Example cfg.zk2s.json:
```
{
	"userAgent": "some dude",
	"templateFile": "response.tmpl",
	"teams": [
		{
			"botToken": "some token",
			"channels": [
				{
					"channelName": "killmails",
					"minimumValue": 0,
					"excludeLosses": "true",
					"includeAlliances": [
						"some alliance name"
					]
				},
				{
					"channelName": "lossmails",
					"minimumValue": 1000000,
					"excludeKills": "true",
					"includeAlliances": [
						"some alliance name"
					]
				},
				{
					"channelName": "management",
					"minimumValue": 1000000000,
					"excludeKills": "true",
					"includeAlliances": [
						"some alliance name"
					]
				}
			]
		}
	]
}
```

**Comment by vivace-io** [comment]
Howdy o/

Glad  to see it is getting some use! 

Just to make sure I'm understanding you correctly, when `excludeKills` is true and the criteria of the filter apply, the expected behavior is the killmail is **not** posted to the channel, yes?

Let me know, and I can probably have this done for you later today!

**Comment by vivace-io** [comment]
Also, with how things work currently, a "loss" is considered to be a killmail in which a watched entity (i.e. corporation/alliance/character) loses their ship. I'm assuming this is fine with what you had in mind?

**Comment by vivace-io** [comment]
New release is out [here.](https://github.com/eveopsec/zk2s/releases/tag/v2.2)

Closing this issue for now, please re-open it, or make a new one if it's not working for you.

P.S. Yes, the commit says PR instead if issue... oh well.
